api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        resources:
            articles:
                normalization_context:
                    groups: ['articles:read']
                types: ['https://schema.org/Article']
                operations:
                    get:
                    post:
                    delete:
                        controller: App\Controller\ArticlesController::delete
    patch_formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
        multipart:
            mime_types: ['multipart/form-data']

    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
        multipart:
            mime_types: ['multipart/form-data']    